### PR TITLE
use div for surrounding parsed content.

### PR DESCRIPTION
**Pull request by mightyplow**
see issue #24

### CODE REVIEW

**Comment by davidowens** [comment]
better still would be to make this an option/prop on the `<Markdown />` component, the same way as `container` works

**Comment by beausmith** [comment]
As https://github.com/acdlite/react-remarkable/pull/33 allows container tag to be specified as a prop, I suggest closing this PR.

**Comment by beausmith** [comment]
@mightyplow But, if you're going to close this issue… merge #33 yo! 👯

**Comment by mightyplow** [comment]
Hi,

as I understood it, there is now a prop for setting the content wrapper,
isn't it?

Cheers,

mightyplow

Beau Smith <notifications@github.com> schrieb am Di., 7. Aug. 2018, 20:53:

**Comment by beausmith** [comment]
I replied, thinking the repo owner closed this issue. Then deleted my
comment after realizing my mistake.

Please add your support to Issue #33 so that we can get that feature merged
by @acdlite!

**Pull request closed without merging**
