### PR TITLE
Update package.json

### LINKED ISSUE #2: not running under react 0.13.x
basically it's just caused by having a dependency on react:

https://github.com/acdlite/react-remarkable/blob/master/package.json#L11

removing the dependency on react would fix this.

### PR DESCRIPTION
**Pull request by azu**
fix #2
- Update react
- Use Babel instead of 6to5

> common is now commonStrict and commonInterop is now common.
> https://github.com/babel/babel/issues/242

### CODE REVIEW

**Comment by acdlite** [comment]
Thanks!

**Comment by azu** [comment]
No problem. please update npm too :bow:

**Comment by acdlite** [comment]
Done :)

**Comment by azu** [comment]
Thanks!

**Pull request merged**
